### ISSUE TITLE
RegJump broken

### ISSUE THREAD

**Issue by fangly** [robertcollier4/REG#6]
Hi Robert,

You plugin seems great, thanks!
However, after a fresh install in Sublime 3 Build 3126 (no changes in preferences), the RegJump functionality does not seem to work.

1/ In the console, the following error message appears: 
> Traceback (most recent call last):
>   File "./python3.3/subprocess.py", line 1104, in _execute_child
> FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\qc\zoe_home\ZoeDev\sublime_text3\sublime_plugin.py", line 818, in run_
>     return self.run(edit)
>   File "jumptoregkey in C:\qc\zoe_home\ZoeDev\sublime_text3\Data\Installed Packages\REG.sublime-package", line 20, in run
>   File "./python3.3/subprocess.py", line 819, in __init__
>   File "./python3.3/subprocess.py", line 1110, in _execute_child
> FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

It seems as if the regjump executable is not found. I suspect this may be related to #3. See the SublimeREPL repo which has [subprocess code](https://github.com/wuub/SublimeREPL/blob/master/repls/subprocess_repl.py ) and includes a [`.no-sublime-package` file](https://github.com/wuub/SublimeREPL/commit/8921a633d71851b1a25ba6b8ce0db4618d60be59).

2/ When an invalid reg key is handled by RegJump, an appropriate error message is issued to the console. The problem is that the message will be missed most of the time (since the console is likely rarely open), and the user has the impression that the RegJump function does not work. Could you perhaps issue the message in a popup, e.g. with `sublime.message_dialog("hello")`?

Cheers,

Florent

**Comment by fangly** [comment]
PS/ A `.gitignore` file seems to be distributed with REG. You may want to exclude it from the package.

**Comment by robertcollier4** [comment]
Duplicates #3
